import type { BuildDisplayData } from '@/types/display'

export const MOCK_BUILDS: BuildDisplayData[] = [
  {
    id: 'mossy-oak-cottage',
    name: 'Mossy Oak Cottage',
    palette: ['#5E4028', '#7A5638', '#8AA64A', '#C9B180', '#4B5D2E'],
    difficulty: 'Medium',
    progression: 'Early Game',
    biome: 'Forest',
    dims: '12 × 8 × 10',
    steps: 24,
    status: 'in-progress',
    progress: { current: 9, total: 24 },
  },
  {
    id: 'lantern-tower',
    name: 'Blackstone Lantern Tower',
    palette: ['#1E1A1E', '#3C2F30', '#E8A23A', '#8B6B3F', '#0F0D10'],
    difficulty: 'Hard',
    progression: 'Mid Game',
    biome: 'Nether',
    dims: '9 × 22 × 9',
    steps: 41,
    status: 'todo',
  },
  {
    id: 'koi-pond',
    name: 'Willow Koi Pavilion',
    palette: ['#C47B5C', '#E8C9A3', '#6FA5A0', '#3E5A48', '#D8526E'],
    difficulty: 'Beginner',
    progression: 'Early Game',
    biome: 'Plains',
    dims: '16 × 6 × 14',
    steps: 18,
    status: 'completed',
  },
  {
    id: 'deepslate-vault',
    name: 'Deepslate Vault Chamber',
    palette: ['#1B2330', '#2E3A4E', '#00B0D9', '#5A6A80', '#0A0D12'],
    difficulty: 'Expert',
    progression: 'End Game',
    biome: 'Cave',
    dims: '24 × 18 × 24',
    steps: 67,
    status: 'in-progress',
    progress: { current: 31, total: 67 },
  },
  {
    id: 'cherry-bridge',
    name: 'Cherrywood Rope Bridge',
    palette: ['#E8A0B8', '#C46A8A', '#6B4A35', '#A88968', '#F7D6DE'],
    difficulty: 'Easy',
    progression: 'Early Game',
    biome: 'Cherry Grove',
    dims: '20 × 5 × 4',
    steps: 12,
    status: 'todo',
  },
  {
    id: 'obsidian-spire',
    name: 'Obsidian Observatory',
    palette: ['#0F0A17', '#2A1E3D', '#7E5BC4', '#C5B0E6', '#060408'],
    difficulty: 'Hard',
    progression: 'Late Game',
    biome: 'End',
    dims: '14 × 28 × 14',
    steps: 52,
    status: 'completed',
  },
]

export const MOCK_COMPACT: BuildDisplayData[] = [
  {
    id: 'r1',
    name: 'Birch Boathouse',
    palette: ['#E4D7AE', '#B29765', '#6C8FAE', '#4E6678', '#D4C58B'],
    difficulty: 'Easy',
    progression: 'Early Game',
    dims: '10 × 6 × 14',
    steps: 16,
    status: 'todo',
  },
  {
    id: 'r2',
    name: 'Sandstone Oasis',
    palette: ['#E8C884', '#C9A15A', '#5EAE9E', '#2F6D5E', '#8FD9C7'],
    difficulty: 'Medium',
    progression: 'Mid Game',
    dims: '18 × 9 × 18',
    steps: 29,
    status: 'in-progress',
    progress: { current: 12, total: 29 },
  },
  {
    id: 'r3',
    name: 'Ice Peak Lodge',
    palette: ['#C8DEEC', '#7AA3C0', '#3D5C78', '#E8EEF4', '#1E3144'],
    difficulty: 'Hard',
    progression: 'Mid Game',
    dims: '14 × 12 × 16',
    steps: 38,
    status: 'todo',
  },
  {
    id: 'r4',
    name: 'Mushroom Hollow',
    palette: ['#B85050', '#E8E8E8', '#8B3838', '#5C3A2E', '#F2D4A8'],
    difficulty: 'Beginner',
    progression: 'Early Game',
    dims: '9 × 7 × 9',
    steps: 14,
    status: 'completed',
  },
]
