/**
 * types/build.ts
 *
 * TypeScript interfaces for Minecraft build designs — the core data model.
 * Rows in the `builds` Supabase table map 1-to-1 with MinecraftBuild.
 */

/** Broad classification of a build to drive UI filtering. */
export type BuildCategory =
  | 'house'
  | 'farm'
  | 'storage'
  | 'decoration'
  | 'redstone'
  | 'landmark'
  | 'underground'
  | 'other'

/** Minecraft edition for material/mechanic compatibility notes. */
export type Edition = 'java' | 'bedrock' | 'both'

/** Rough difficulty rating shown in the UI. */
export type Difficulty = 'easy' | 'medium' | 'hard' | 'expert'

/** A single material line item in the build's shopping list. */
export interface MaterialItem {
  id: string
  name: string
  /** Minecraft item ID, e.g. "minecraft:oak_log" */
  minecraftId: string
  quantity: number
  /** Quantity the player has gathered so far — tracked client-side and persisted. */
  gathered: number
  /** Block texture image URL (optional, from assets). */
  textureUrl?: string
}

/** A sequential step within a build phase. */
export interface BuildStep {
  id: string
  order: number
  description: string
  /** Optional tips or warnings for this step. */
  note?: string
  isCompleted: boolean
}

/** A named phase grouping multiple steps (e.g. "Foundation", "Walls", "Roof"). */
export interface BuildPhase {
  id: string
  name: string
  order: number
  steps: BuildStep[]
}

/** Approximate 3-D footprint in blocks. */
export interface BuildDimensions {
  width: number
  height: number
  depth: number
}

/** The full build document as stored in Supabase and used throughout the app. */
export interface MinecraftBuild {
  id: string
  userId: string
  title: string
  description: string
  category: BuildCategory
  difficulty: Difficulty
  edition: Edition
  dimensions: BuildDimensions
  /** Estimated time to complete in minutes. */
  estimatedMinutes: number
  materials: MaterialItem[]
  phases: BuildPhase[]
  /** Raw markdown from the AI — displayed in the BuildDetail view. */
  markdownInstructions: string
  /** Whether the build was generated by AI or created manually. */
  isAiGenerated: boolean
  /** Freeform tags for searching / filtering. */
  tags: string[]
  /** Cover image URL (screenshot or generated). */
  imageUrl?: string
  isFavorite: boolean
  createdAt: string
  updatedAt: string
}

/** Payload sent to the AI build-generation edge function. */
export interface BuildGenerationRequest {
  prompt: string
  category?: BuildCategory
  difficulty?: Difficulty
  edition?: Edition
  maxBlocks?: number
  styleNotes?: string
}

/** Response shape returned by the edge function after AI generation. */
export interface BuildGenerationResponse {
  build: Omit<MinecraftBuild, 'id' | 'userId' | 'isFavorite' | 'createdAt' | 'updatedAt'>
  tokensUsed: number
}
